### ISSUE TITLE
PNGs are exported in a cropped form

### ISSUE THREAD

**Issue by CommanderStorm** [just-max/exzellenz#5]
If you try to export a PNG with 1000px as height they are visibly cut down, by a viewbox.

**Comment by just-max** [comment]
Interesting. Also happens for SVG export. Fixing might be tricky because measuring text size in SVGs precisely is hard.

**Comment by just-max** [comment]
Which browser are you using? I can recreate the issue in Chrome on Android and Chromium on Linux, but Firefox has no issues. For example, this image was generated with height 1000px.
![image](https://user-images.githubusercontent.com/17551908/150190017-21fa22e1-c7b7-48f2-b38a-b216cbaf722c.png)

That makes the issue especially annoying to fix. For now, just use Firefox :smirk:

**Comment by CommanderStorm** [comment]
Verry interesting.
`Exzellenz` has been a better test string for me.
I probably should have gone through the normal web-debugging steps, before leaving a half-baked bug-report.

I too use Chromium on Linux 

That it works on firefox is weird..
Given the scope (and usage) of the procject a simple "⚠️This project does only work properply on firefox ⚠️" would resolve this issue imo.

**Comment by just-max** [comment]
> Given the scope (and usage) of the procject a simple "warningThis project does only work properply on firefox warning" would resolve this issue imo.

But that's no fun...

Changing the size (specifically: the width, e.g. to `0 0 1000 100`) of the SVG viewbox here
https://github.com/just-max/exzellenz/blob/5405d2b75b5921aabb5ebd8a604b047b5798e7e0/docs/generator.js#L140
"fixes" the issue. A simple workaround is then to scale the initial size of the viewbox based on the length of the string and the font size.

Upon further investigation, it looks like chrome doesn't provide proper bounding boxes (`getBBox`) for elements many times larger than the viewbox. The cutoff seems to be "hard", too, i.e. `getBBox` works up to some maximum size and then keeps returning the same value.

The [following demo](https://gist.github.com/just-max/7b410a6178e49276e65086c3b1f4c3e6) isolates the issue (see the first comment).

Not sure if this is a bug in Chrome or just unintended use of the API :thinking:
